#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WRKDIR = `pwd`
MAKE = make

all: bullettest_bullettest_linux

bullettest_bullettest_linux: 
	$(MAKE) -C BulletTest all

clean: clean_bullettest_bullettest_linux

clean_bullettest_bullettest_linux: 
	$(MAKE) -C BulletTest clean

.PHONY: clean_bullettest_bullettest_linux

